<?php

// src/AM/IdeaMachineBundle/Entity/IdeaRepository.php

namespace AM\IdeaMachineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IdeaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdeaRepository extends \Doctrine\ORM\EntityRepository
{
	public function getIdeaWithVotes(){
		$qb = $this
		->createQueryBuilder('a')
		->leftJoin('a.votes', 'app')
		->addSelect('app');

		return $qb
		->getQuery()
		->getResult();
	}

	public function getIdeas(){
		$query = $this->createQueryBuilder('a')
		->leftJoin('a.image', 'i')
		->addSelect('i')
		->leftJoin('a.votes', 'v')
		->addSelect('v')
		->orderBy('a.id', 'DESC')
		->getQuery();

		return $query->getResult();
	}

	public function getIdeaUser($idUser)
	{
		$qb = $this->createQueryBuilder('a');

		// On fait une jointure avec l'entité Category avec pour alias « c »
		$qb
		->innerJoin('a.user', 'u')
		->addSelect('u');

		// Puis on filtre sur le nom des catégories à l'aide d'un IN
		$qb->where('u.id = :idUser');
		$qb->setParameter('idUser', $idUser);

		// Enfin, on retourne le résultat
		return $qb
		->getQuery()
		->getResult();
	}
}