<?php

// src/AM/IdeaMachineBundle/Entity/VoteRepository.php

namespace AM\IdeaMachineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends \Doctrine\ORM\EntityRepository
{
	
}