am_idea_machine_home:
    path:      /
    defaults: { _controller: AMIdeaMachineBundle:Idea:index }

am_platform_view:
    path:      /idea/view/{slug}
    defaults: { _controller: AMIdeaMachineBundle:Idea:view }

am_platform_add:
    path:      /idea/add
    defaults: { _controller: AMIdeaMachineBundle:Idea:add }

am_platform_edit:
    path:      /idea/edit/{slug}
    defaults: { _controller: AMIdeaMachineBundle:Idea:edit }

am_platform_delete:
    path:     /idea/delete/{slug}
    defaults: { _controller: AMIdeaMachineBundle:Idea:delete }

am_platform_mine:
    path:     /idea/mine
    defaults: { _controller: AMIdeaMachineBundle:Idea:mine }

am_platform_get_other_idea:
    path:     /idea/other-idea
    defaults: { _controller: AMIdeaMachineBundle:Idea:getOtherIdea }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"