am_idea_machine_home:
    path:      /
    defaults: { _controller: AMIdeaMachineBundle:Idea:index }

am_platform_view:
    path:      /view/{slug}
    defaults: { _controller: AMIdeaMachineBundle:Idea:view }

am_platform_add:
    path:      /add
    defaults: { _controller: AMIdeaMachineBundle:Idea:add }

am_platform_edit:
    path:      /edit/{slug}
    defaults: { _controller: AMIdeaMachineBundle:Idea:edit }

am_platform_delete:
    path:     /delete/{slug}
    defaults: { _controller: AMIdeaMachineBundle:Idea:delete }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"